version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - './jenkins:/var/jenkins_home'
volumes:
  jenkins:
    driver: local
